### ISSUE TITLE
I want to add BMI Calculator - Java Program

### ISSUE THREAD

**Issue by minhaj-313** [Anuragcoderealy/Codenewhacktober#29]
I want to add BMI Calculator - Java Program - It is used to find the Body Mass Index -
Please Assign  me under Hacktoberfest

**Comment by Anuragcoderealy** [comment]
Just create and pull request I will assign while merging .

**Comment by minhaj-313** [comment]
> Just create and pull request I will assign while merging .

Ok Thanks

**Comment by minhaj-313** [comment]
@Anuragcoderealy  I sent PR please Merge it, label as hacktober-accepted.
Thank You
